apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default
type: Opaque
data:
  DB_PASSWORD: "cGFzc3dvcmQ="  # Base64-encoded value of "password"
  API_KEY: "MTIzNDU2Nzg5"  # Base64-encoded value of "123456789"
