apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: default
spec:
  containers:
    - name: my-container
      image: busybox
      command: [ "sh", "-c", "env && sleep 3600" ]  # Keeps the container running
      env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: APP_NAME
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: LOG_LEVEL
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_PASSWORD
