apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80          # Port exposed internally within the cluster
      targetPort: 80    # Port on the pod
      nodePort: 30007   # Port exposed on the node
