---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  nodeName: controlplane  #add nodeName to manually schedule pods in absence of a schedular
  containers:
  -  image: nginx
     name: nginx

                                                                                