apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
#equivalent command in docker = docker run --d nginx:1.14.2 --name nginx -p 80:80